name: Kangaroo Solver
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  solve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Download Pre-built Kangaroo
        run: |
          wget https://github.com/JeanLucPons/Kangaroo/releases/download/v2.2/kangaroo_linux
          chmod +x kangaroo_linux
          
      - name: Run Kangaroo (Test Mode)
        run: |
          ./kangaroo_linux -h  # تست اجرا
