name: Kangaroo Solver
on:
  workflow_dispatch:  # اجازه اجرای دستی
  schedule:
    - cron: '0 */6 * * *'  # هر ۶ ساعت اجرا شود

jobs:
  solve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgmp-dev

      - name: Clone & Build Kangaroo
        run: |
          git clone https://github.com/JeanLucPons/Kangaroo.git
          cd Kangaroo
          make

      - name: Run Kangaroo
        run: |
          cd Kangaroo
          ./kangaroo -range 1:100000000 -target 1EzVHtmbN4fs4MiNK3ppEnKKhsmXYJ4s74
