name: Kangaroo Solver
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  solve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgmp-dev

      - name: Clone & Build Kangaroo (Simplified)
        run: |
          git clone https://github.com/JeanLucPons/Kangaroo.git
          cd Kangaroo
          make gpu=0  # غیرفعال کردن GPU برای جلوگیری از خطا

      - name: Run Kangaroo (Test Mode)
        run: |
          cd Kangaroo
          ./kangaroo -h  # فقط نمایش راهنما برای تست اولیه
